/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as QuizIndexRouteImport } from './routes/quiz/index'
import { Route as QuizProgressRouteRouteImport } from './routes/quiz/_progress/route'
import { Route as QuizStartRouteImport } from './routes/quiz/start'
import { Route as QuizProgressStepRouteImport } from './routes/quiz/_progress/$step'
import { Route as QuizProgressReviewRouteImport } from './routes/quiz/_progress/review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizProgressRouteRoute = QuizProgressRouteRouteImport.update({
  id: '/quiz/_progress',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizStartRoute = QuizStartRouteImport.update({
  id: '/quiz/start',
  path: '/quiz/start',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizProgressStepRoute = QuizProgressStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => QuizProgressRouteRoute,
} as any)
const QuizProgressReviewRoute = QuizProgressReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => QuizProgressRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/quiz': typeof QuizProgressRouteRouteWithChildren
  '/quiz/start': typeof QuizStartRoute
  '/quiz/': typeof QuizIndexRoute
  '/quiz/$step': typeof QuizProgressStepRoute
  '/quiz/review': typeof QuizProgressReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/quiz': typeof QuizIndexRoute
  '/quiz/start': typeof QuizStartRoute
  '/quiz/$step': typeof QuizProgressStepRoute
  '/quiz/review': typeof QuizProgressReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/leaderboard': typeof LeaderboardRoute
  '/quiz/_progress': typeof QuizProgressRouteRouteWithChildren
  '/quiz/start': typeof QuizStartRoute
  '/quiz/': typeof QuizIndexRoute
  '/quiz/_progress/$step': typeof QuizProgressStepRoute
  '/quiz/_progress/review': typeof QuizProgressReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/leaderboard'
    | '/quiz'
    | '/quiz/start'
    | '/quiz/'
    | '/quiz/$step'
    | '/quiz/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/leaderboard'
    | '/quiz'
    | '/quiz/start'
    | '/quiz/$step'
    | '/quiz/review'
  id:
    | '__root__'
    | '/'
    | '/leaderboard'
    | '/quiz/_progress'
    | '/quiz/start'
    | '/quiz/'
    | '/quiz/_progress/$step'
    | '/quiz/_progress/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LeaderboardRoute: typeof LeaderboardRoute
  QuizProgressRouteRoute: typeof QuizProgressRouteRouteWithChildren
  QuizStartRoute: typeof QuizStartRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/quiz'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/_progress': {
      id: '/quiz/_progress'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizProgressRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/start': {
      id: '/quiz/start'
      path: '/quiz/start'
      fullPath: '/quiz/start'
      preLoaderRoute: typeof QuizStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/_progress/$step': {
      id: '/quiz/_progress/$step'
      path: '/$step'
      fullPath: '/quiz/$step'
      preLoaderRoute: typeof QuizProgressStepRouteImport
      parentRoute: typeof QuizProgressRouteRoute
    }
    '/quiz/_progress/review': {
      id: '/quiz/_progress/review'
      path: '/review'
      fullPath: '/quiz/review'
      preLoaderRoute: typeof QuizProgressReviewRouteImport
      parentRoute: typeof QuizProgressRouteRoute
    }
  }
}

interface QuizProgressRouteRouteChildren {
  QuizProgressStepRoute: typeof QuizProgressStepRoute
  QuizProgressReviewRoute: typeof QuizProgressReviewRoute
}

const QuizProgressRouteRouteChildren: QuizProgressRouteRouteChildren = {
  QuizProgressStepRoute: QuizProgressStepRoute,
  QuizProgressReviewRoute: QuizProgressReviewRoute,
}

const QuizProgressRouteRouteWithChildren =
  QuizProgressRouteRoute._addFileChildren(QuizProgressRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LeaderboardRoute: LeaderboardRoute,
  QuizProgressRouteRoute: QuizProgressRouteRouteWithChildren,
  QuizStartRoute: QuizStartRoute,
  QuizIndexRoute: QuizIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
